# Generated by Django 4.1.7 on 2023-03-01 16:56

from django.db import migrations


def create_groups(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_blog = Permission.objects.get(codename='add_blog')
    view_blog = Permission.objects.get(codename='view_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')

    creators_permissions = [
        add_blog,
        view_blog,
        change_blog,
        delete_blog
    ]
    creators = Group(name='creators')
    creators.save()
    creators.permissions.set(creators_permissions)

    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.add(view_blog)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
