# Generated by Django 4.1.7 on 2023-03-01 19:14

from django.db import migrations


def complete_groups(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_photo = Permission.objects.get(codename='add_photo')

    creators = Group.objects.get(name='creators')
    creators.permissions.add(add_photo)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230301_1656'),
    ]

    operations = [
        migrations.RunPython(complete_groups)
    ]
